### DISCUSSION TITLE
How to set setuptools_scm local_scheme through hatch vcs options?

### DISCUSSION THREAD

**Discussion by matthewfeickert** [ofek/hatch-vcs#12] [Q&A] [answered]
For reasons [described elsewhere](https://github.com/pypa/setuptools_scm/issues/455) it can be helpful when having version numbers be determined through the vcs through `hatch-vcs` (and so eventually `setuptools_scm`) to be able to [`setuptools_scm`'s `local_scheme` option set to `"no-local-version`](https://github.com/pypa/setuptools_scm/blob/e1283177b23ccf254739aa8292448154c54741c8/README.rst#version-number-construction) so that the version number will be [PEP 440 compliant](https://github.com/pypa/pypi-legacy/issues/731).

For a `setuptools` based build I would do this with the following `pyproject.toml`

```toml
[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=61.0.0", "setuptools_scm>=7.0.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/package_name/_version.py"
local_scheme = "no-local-version"
```

but how do I tell `hatch-vcs` to tell `setuptools_vcs` to use

```toml
local_scheme = "no-local-version"
```

?

This is my current `pyproject.toml` for the project I'm attempting this for

```toml
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "package_name"
...
dynamic = ["version"]

...

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/package_name/version.py"
```

Attempting to add

```toml
build.hooks.vcs.local_scheme = "no-local-version"
```

doesn't work. Apologies if I've missed something in the docs!

**Comment by ofek** [comment, marked as answer]
Hello! `raw-options` https://github.com/ofek/hatch-vcs#version-source-options

**Reply by matthewfeickert** [reply]
Thanks! For others this is what my revised `pyproject.toml` has in it now. :+1: 

```toml
...

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/package_name/version.py"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"
```
