### DISCUSSION TITLE
What is the recommended GitHub Action checkout to get all metadata needed for version?

### DISCUSSION THREAD

**Discussion by ketozhang** [ofek/hatch-vcs#66] [Q&A]
I understand by default, https://github.com/actions/checkout, does a shallow copy which is not enough for hatch-vcs to fetch the latest version.

I've not tested 

- Tags only fails

    ```yaml
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-tags: true
    ```

- Full history is the extreme end, but can we have less?

    ```yaml
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
    ```
