### ISSUE TITLE
Recommended way to use the build hook

### ISSUE THREAD

**Issue by maresb** [ofek/hatch-vcs#13]
I'm trying to understand [this comment](https://github.com/mariusvniekerk/condax/pull/59#discussion_r976457588) recommending against setting `__version__` with `importlib.metadata.version` when startup time is important (e.g. CLI).

Is this the sort of setup you had in mind?

`hatch_vcs_example/__init__.py`
```python
# Set the value of '__version__'
try:
    # If setuptools_scm is installed (e.g. in a development environment),
    # then use it to determine the version dynamically.
    from setuptools_scm import get_version

    __version__ = get_version(root="..", relative_to=__file__)
except ImportError:
    # If setuptools_scm is not installed (e.g. in a release environment),
    # then use the version that is hard-coded in the file.
    try:
        from hatch_vcs_example._version import __version__  # noqa: F401
    except ModuleNotFoundError:
        raise RuntimeError(
            f"{__name__} is not correctly installed. Please install it with pip."
        )
```

`pyproject.toml`
```toml
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "hatch-vcs-example"
dynamic = ["version"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "hatch_vcs_example/_version.py"
```

`.gitignore`
```
hatch_vcs_example/_version.py
```

Initialization:
```bash
git init
git commit --allow-empty -m "Initial commit"
git tag v1.2.3
pip install .
```

Result:

`hatch_vcs_example/_version.py`
```python
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.2.3'
__version_tuple__ = version_tuple = (1, 2, 3)
```

On my computer this saves about 40 ms (63 ms vs 23 ms).

I was thinking it could be useful to add this to the README, but it's a bit long. But in terms of impact, I think adding a minimalist example like

```toml
[tool.hatch.build.hooks.vcs]
version-file = "_version.py"
```

would go a long ways towards making the version-file feature more visible.
