### ISSUE TITLE
Likely user error - help understanding the write_to template implementation in hatch vcs

### ISSUE THREAD

**Issue by lwasser** [ofek/hatch-vcs#60]
Hey there @ofek and other hatch_vcs maintainers!! 

i'm moving a project over to hatchling now and also working on a tutorial. I wondered if you could help me understand the write_to template element here. Below are the important parts of my pyproject.toml file related to vcs versioning

```toml
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "pyosmeta"
dynamic = ["version"]
description = "Tools that update the pyOpenSci contributor and review metadata that is posted on our website"
authors = [{ name = "Leah Wasser", email = "leah@pyopensci.org" }]
maintainers = [
    { name = "pyOpenSci", email = "admin@pyopensci.org" }, # Optional
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only", 
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[project.optional-dependencies]
dev = [
  "pre-commit",
  "build"
]

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/pyosmeta/_version.py"
# If you're using a v in the version you have to create a template
build.hooks.vcs.template = '__version__ = "v{version}"'
```

i'm trying to create a template so it recognizes my tags having a "v" in front of them. 

```bash
❯ git tag 
v0.2
```
but hatch build returns 

```
> hatch build
hatch version
0.1.dev156+g79247d1.d20231220
```

And of course, when I run `python -m build` you can see that the package version is 0.1 dev instead of 0.2 dev. i unpacked the wheel and see the same thing in the METADATA. I"m certain this is user error but there is a translation step in migrating from setuptools_Scm --> hatch_vcs that i don't understand yet. 

```

➜ python -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatch-vcs, hatchling)
* Getting build dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatch-vcs, hatchling)
* Getting build dependencies for wheel...
* Building wheel...
Successfully built pyosmeta-0.1.dev156+g79247d1.d20231220.tar.gz and pyosmeta-0.1.dev156+g79247d1.d20231220-py3-none-any.whl
```

i've also tried this:

`build.hooks.vcs.template = "v{version}"`

in case it just wanted the template text.

Are you able to help me understand what step i'm missing here to ensure the version template is read correctly? Many thanks!
