### ISSUE TITLE
Support building in a subdirectory of the Git repository

### ISSUE THREAD

**Issue by gipert** [ofek/hatch-vcs#65]
Is it possible to specify the location of the `.git` directory? In my use case, the package is located in a subdirectory and pip-installing fails.
```
repo/
  |- .git/
  `- package/
       `- pyproject.toml
```

**Comment by ofek** [comment]
```toml
[tool.hatch.version]
source = "vcs"
raw-options = { root = ".." }
```
